return PlaceObj('ModDef', {
	'title', "Terraforming Interconnected",
	'description', "Makes Terraforming parameters interconnected.",
	'id', "qVR4gnq",
	'pops_desktop_uuid', "4e8456c2-3ae3-4d44-b1ab-46b421aba7f4",
	'pops_any_uuid', "b5308af6-d37d-4c24-bf02-7cf8950af93c",
	'author', "tanyfilina",
	'version', 2,
	'lua_revision', 233360,
	'saved_with_revision', 249143,
	'code', {
		"Code/ScriptParameters.lua",
		"Code/ScriptInfopanel.lua",
		"Code/ScriptBuildings.lua",
		"Code/ScriptTechs.lua",
		"Code/ScriptMissions.lua",
		"Code/Class_RDM_GeoPowerPlant.lua",
		"Code/Init.lua",
		"Code/SavegameFix.lua",
		"Code/ScriptClasses.lua",

	},
	'saved', 1578910764,
	'TagGameplay', true,
	'TagTerraforming', true,
})